//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudOperations2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hobby
    {
        public int idhobbies { get; set; }
        public string hobbiesName { get; set; }
        public Nullable<bool> isselected { get; set; }
    }
}
